### ISSUE TITLE
Recuperar campo "Cargo" em contatos

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/centers-wp-plugin#10]
@viniciusandrade 

É possível recuperar ao lado do nome/contato o campo cargo?

Exemplo: BR49.1

![image](https://user-images.githubusercontent.com/38661168/83895984-d8bd3e00-a729-11ea-9299-7f50adc4e050.png)

Obrigada!

**Comment by viniciusandrade** [comment]
@alvesmarilda 
Quando você menciona "recuperar" quer dizer mostrar este campo ao lado do Nome na ficha da instituição?

Obrigado

**Comment by alvesmarilda** [comment]
@viniciusandrade 
Sim, mostrar no Diretório.
Exemplo:
Marcelo Pastore Lopes **(Diretor)** | diretoria.bco@ufscar.br | +16 3351-8422
Graziella Yuri Matsuno **(Bibliotecária)** | bcoatendimento2@gmail.com | +16 3351-8424 / 8135

Obrigada!

**Comment by viniciusandrade** [comment]
@alvesmarilda 
OK,  a informação foi adicionada na ficha da institutição.
