### ISSUE TITLE
Inconsistência na pesquisa por cat: ou user: no Diretório da Rede BVS

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/centers-wp-plugin#13]
Vinicius,

As pesquisas que fazemos no Diretório da Rede BVS tem resultados diferentes ao Fi-admin(Instituição).

Exemplos:
Diretório da Rede 
cat:periodico  =  1427 Instituições  
cat:periodico editor  =  2 Instituições
cat:periodico editor$  =   111 Instituições

Fi-admin recupera:  1486 Instituições
![image](https://user-images.githubusercontent.com/38661168/85553590-7bb2fa80-b5fa-11ea-813c-0bd764794fd2.png)

user:refnet  =  27 instituições

![image](https://user-images.githubusercontent.com/38661168/85553783-adc45c80-b5fa-11ea-9258-ff4436ca6522.png)

Fi-admin recupera: 29 instituições

![image](https://user-images.githubusercontent.com/38661168/85554393-39d68400-b5fb-11ea-9b22-d579b4ac9085.png)

Obrigada!

**Comment by viniciusandrade** [comment]
Marilda,

Revisei o sistema e a busca pelos prefixos **user:**  e **cat:** ainda estava usando os campos do histórico da migração e não os campos novos que são os mesmos dos filtros do FI-ADMIN.

Agora acredito que o resultado será condizente com o filtro interno. Lembrando que as buscas por termos compostos precisam estar entre aspas duplas:

cat:"periodico editor"

Favor, quando possível, verificar.

Obrigado.

**Comment by alvesmarilda** [comment]
Vinicius,

Fiz testes neste momento e constatei que o resultado está de acordo com o recuperado no Fi-admin/Instituição.

Obrigada.

**Comment by viniciusandrade** [comment]
Eu que agradeço pela validação.
