### ISSUE TITLE
Pesquisa CCN / Lista de Países incompleta

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/centers-wp-plugin#14]
Vinicius,

Quando seleciono a opção de CCN no Diretório da Rede BVS não consigo visualizar todos os Países(37).

https://bvsalud.org/centros/?filter=institution_type:%22CoordinatingCentersNc%22

![image](https://user-images.githubusercontent.com/38661168/88967256-ea334a00-d283-11ea-831d-952c032fc26d.png)
País
Albânia (1)
Antigua e Barbuda (1)
Argentina (1)
Bahamas (1)
Barbados (1)
Belize (1)
Bolívia (1)
Brasil (1)
Cayman, Ilhas (1)
Chile (1)
Colômbia (1)
Costa Rica (1)
Cuba (1)
Dominicana, República (1)
Dominica (1)
Equador (1)
El Salvador (1)
Granada (1)
Guatemala (1)
Guiana (1)

Obrigada!

**Comment by viniciusandrade** [comment]
Marilda,
O sistema possui a limitação de mostrar as 20 maiores posições por quantidade de instituições  do filtro e não temos ainda como no Portal de Pesquisa a opção "Mostrar mais ..." 

Vou deixar este issue em aberto para quando for possível realizarmos a implementação desta opção.

**Comment by alvesmarilda** [comment]
Vinicius,
Qual seria a opção para recuperar o CCN da Nicarágua?
Somente rolagem de páginas? Visualizando cada registro?

**Comment by viniciusandrade** [comment]
No momento acredito que somente por rolagem de páginas após aplicar o filtro de CCN.

**Comment by barrosjo** [comment]
@viniciusandrade retomando esse tema. Essa semana tive a mesma dificuldade para identificar os centros cooperantes da Costa Rica (somente 3) e explicar para os coordenadores da BVS no país. Minha sugestão, além de disponibilizar o "Mostrar mais" urgente, é disponibilizar os 3 clusters (Rede BVS, Redes Temáticas e País) por ordem alfabética, para facilitar a navegação.

**Comment by viniciusandrade** [comment]
@alvesmarilda e @barrosjo foi adicionado a opção "mostrar mais" para o filtro de países do diretório para permitir visualizar a lista completa.

Favor realizar um shift+refresh do navegador na página do diretório para atualizar os componentes da página.

Agradeço ao @wilsonmoura por ter implementado este recursos nos demais plugins e possibilitar esta opção.

**Comment by alvesmarilda** [comment]
ok!  Obrigada!
