### ISSUE TITLE
Recuperação Editores no Diretório

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/centers-wp-plugin#15]
Vinicius,
Estou documentando o que havíamos solicitado por e-mail em relação a recuperação dos registros de editores.

Alves, Marilda Perez (BIR)
Ter, 14/07/2020 14:32

Analisando o Diretório da Rede BVS verifiquei que os códigos editores estão em destaque devido à atualização da rede de editores.
Esta recuperação pode trazer dúvidas aos usuários, pois nem sempre conseguimos identificar que o registro recuperado é editor
No antigo Diretório o editor somente era recuperado digitando o código do mesmo ou fazendo a busca através da pesquisa
cat=periodico editor.

Conversando com Sueli constatamos a necessidade de reconhecimento da rede de Editores e sugerimos que este códigos sejam recuperados através da opção:

![image](https://user-images.githubusercontent.com/38661168/88972339-c07e2100-d28b-11ea-9cfb-ba1e9f7ea2e9.png)

**EDITORES**

A recuperação dos editores será somente ao selecionar a opção sugerida.

Aguardo sua resposta.

Obrigada!

**Comment by viniciusandrade** [comment]
@alvesmarilda foi criado nova entrada no filtro **Rede BVS** para Editores.

Favor, quando possível validar. Obrigado.

**Comment by alvesmarilda** [comment]
Verificação ok.  validado


Obrigada!
