### ISSUE TITLE
Recuperar somente as Instituições da Rede 

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/centers-wp-plugin#16]
O diretório ainda está mostrando o número total de registros que foram exportados da Nmail para o Fi-admin.

Cópia e-mail enviado em 03/06.

Abdala, Carmen Veronica Mendes (BIR)
Qua, 3/6/2020 15:43
Marilda, Vinicius, 
eu sugiro separar e colocar estes usuários categoria I (não Rede) como Outros, e não misturar com os que são Rede. 

obrigada, Veronica

Verônica Abdala
Gerente SCI – Serviços Cooperativos de Informação
Gerente PFI – Produção de Fontes de Informação
BIREME / OPAS / OMS 

Alves, Marilda Perez (BIR)
Ter, 2/6/2020 14:23
Verônica, Boa Tarde!

Há uma inconsistência em relação ao número de Centros em nosso Diretório da Rede a seguir:

Conforme Vinicius informou em uma das reuniões que participamos sobre o novo diretório no Fi-admin, foram importados da Nmail os seguintes usuários: Tipo=I and not BRI$
Todos os usuários tipo"Institucionais" retirando os códigos  BRI (usuário individual).
Não levou em conta somente os usuários tipo=Rede$
Ele informou que achou mais seguro para não perder os registros de usuários Institucionais que poderiam ser categorizados posteriormente como "Rede".

O excedente dos usuários que não são "Rede$" = 3195
Usuários "Rede$" e Periódico Editor = 3046

Iremos manter os usuários excedentes (não rede) no diretório da rede?
Mantemos no sistema Fi-admin todos e solicitamos a recuperação no diretório somente da "Rede$" e categoria Periódico Editor?
Solicitamos apagar todos os excedentes(não rede) no Fi-admin?

Aguardo sua posição.

Obrigada!

Marilda Perez Alves

**Comment by viniciusandrade** [comment]
@alvesmarilda conforme informado para a recuperação somente das instituições da rede foi aplicado o seguinte filtro inicial:
**(user:rede$ OR cat:editor$)**

Agradeço, quando possível validar no diretório da rede bvs (https://bvsalud.org/centros/)

Obrigado

**Comment by alvesmarilda** [comment]
Verificado. validado ok.

Obrigada!

**Comment by alvesmarilda** [comment]
Vinicius, Boa Tarde!

Estava fazendo algumas pesquisas no Diretório e observei que a rede Medcarib não está registrada como "rede" no Fi--admin. Devemos acrescentar a estratégia: user=medcarib$.

Obrigada!

**Comment by viniciusandrade** [comment]
Boa tarde Marilda,

Estratégia atualizada e aplicada no diretório:
**(user:rede$ OR cat:editor$ OR user:medcarib$)**

Favor validar.

**Comment by alvesmarilda** [comment]
ok!  Validado.

Obrigada!
