### ISSUE TITLE
Recuperar Instituições com Status Inativa ou Fechada

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/centers-wp-plugin#17]
Email enviado em:
Alves, Marilda Perez (BIR)
Seg, 29/06/2020 14:30
Vinicius,   Bom Dia!

Caso não seja possível a recuperação no Diretório por Inativa ou Fechada, podem aparecer como Centros Cooperantes ou Unidades Participantes, pois o próprio registro mostra o Status nestes casos:

REDEBR Para bibliotecas inativas ou fechadas(registros/legado/diretório)

REDEAL Para bibliotecas inativas ou fechadas(registros/legado/diretório)

Obrigada!

**Comment by alvesmarilda** [comment]
@viniciusandrade 

Vinicius,

Alguma resposta sobre a pesquisa por Status no Diretório da Rede BVS??

Obrigada
Marilda

**Comment by alvesmarilda** [comment]
Vinicius,
Tentei hoje a busca por Status e consegui recuperar os registros.
Ex: status:1 (ATIVA)  status:2 (INATIVA) status:3 (FECHADA)

Há somente uma diferença de resultado no status:1 
Fi-admin = 5792 Instituições
Diretório = 5789 Instituições
https://bvsalud.org/centros/?lang=pt&q=status%3A1

É possível verificar o que ocorre? 

Obrigada

**Comment by viniciusandrade** [comment]
@alvesmarilda ao longo do tempo é comum que ocorram pequenas diferença entre o FI-ADMIN e a busca do Diretório da Rede BVS por se tratar de diferente sistemas que podem perder o sincronismo entre os dados.

Neste caso eu realizei o processo de sincronismo e agora os valores estão iguais.

Favor validar. Obrigado.

**Comment by alvesmarilda** [comment]
@viniciusandrade Teste realizado com sucesso hoje.

Obrigada!

**Comment by viniciusandrade** [comment]
Eu que agradeço.
