### ISSUE TITLE
Link incorreto

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/centers-wp-plugin#18]
Quando a gente clica em "início", vai para https://bvsalud.org/. Só quando clicamos no logo da BSV que volta pra home do diretório

![image](https://user-images.githubusercontent.com/47643830/98827573-cac8c300-2415-11eb-9634-f50412bd7d05.png)

**Comment by marcoslmori** [comment]
Esses ajustes são feitos na configuração do plugin
