### ISSUE TITLE
Incluir data de atualização dos registros/instituições

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/centers-wp-plugin#19]
Vinicius,
Solicitamos verificar a possibilidade de recuperação no Diretório da Rede BVS quanto a data da última alteração/atualização dos registros/instituições.
Desta forma é possível verificar se os dados apresentados necessitam de atualização.

Obrigada
Marilda

**Comment by viniciusandrade** [comment]
@alvesmarilda conforme conversamos a inclusão da data no diretório poderia causar confusão para os usuários, desta forma foi implementado no FI-ADMIN uma coluna mostrando a data de última atualização do cadastro e colocando em cores diferentes (amarelo > 6 meses / vermelho > 12 meses) esta informação.

Também foi adicionado um filtro na pesquisa do FI-ADMIN para cadastros com data de atualização superiores a 1, 2 e 3 anos.

Favor, quando possível realizar os testes e informar ajustes necessários.
Obrigado

**Comment by alvesmarilda** [comment]
@viniciusandrade 

Verifiquei o Fi-Admin agora e constatei:

1)Até 6 meses sem marcação e após 6 meses marcação em vermelho.

![image](https://github.com/bireme/centers-wp-plugin/assets/38661168/510be54c-d01d-4cb1-8eec-a2677b269c96)

2)O resultado por Updated/years (1,2,3)  talvez mudar a ordem de apresentação: (atualização mais recente primeiro)

![image](https://github.com/bireme/centers-wp-plugin/assets/38661168/8b871c4e-ad69-4f4b-a9ff-e7a31453449e)

![image](https://github.com/bireme/centers-wp-plugin/assets/38661168/30ec4c5a-d1f4-4667-8d26-c7baf07d0be7)

![image](https://github.com/bireme/centers-wp-plugin/assets/38661168/86b740ac-12fd-4e87-9add-415466cc3440)


3)As atualizações processadas em **2019** não são recuperadas pelo respectivo ano, são recuperadas somente com a data de import (03/04/2018) o histórico de mudanças não é recuperado.

Exemplos:
 
https://fi-admin.bvsalud.org/institution/edit/120347#

![image](https://github.com/bireme/centers-wp-plugin/assets/38661168/9aa29913-ab01-476c-a2b1-4999b5bc978a)

![image](https://github.com/bireme/centers-wp-plugin/assets/38661168/8301b3b6-589b-48b3-85cb-ae46d6829803)

**Criado em: 3 de Abril de 2018 às 09:00 pelo usuário import**

![image](https://github.com/bireme/centers-wp-plugin/assets/38661168/9fa9cd8a-fbef-40f3-8acc-d758020c1910)

Outros exemplos: **(Atualizado em 2019**)
https://fi-admin.bvsalud.org/institution/edit/101498  
https://fi-admin.bvsalud.org/institution/edit/194318

4)Termo de adesão consta como atualização:

https://fi-admin.bvsalud.org/institution/edit/201150

![image](https://github.com/bireme/centers-wp-plugin/assets/38661168/0e83d096-9914-4ff5-9f6e-7b4013151c23)

Não aparece em histórico de mudanças as alterações anteriores processadas após o import (3 de Abril de 2018):

![image](https://github.com/bireme/centers-wp-plugin/assets/38661168/ffda1931-e18a-4ca2-b486-8c0a40a05fae)

5)Como recuperar as atualizações processadas em 2023 ou ano vigente?

Obrigada!

**Comment by viniciusandrade** [comment]
Oi @alvesmarilda segue abaixo comentários:

1) A regra implementada foi mostrar na cor vermelha as instituições com data de atualização superior a 1 ano e em laranja as instituições com data de atualização superior a 6 meses.

2) Alterado a ordem de apresentação, favor verificar.

3) Infelizmente não é possível aplicar estas regras para os dados importados, pois o campo normalizado de data de atualização só começou a ser gerado pelo sistema após a importação. Gradativamente quando as instituições antigas foram atualizadas o campo será gerado e será possível fazer o acompanhamento.

4)  Correto

5) Foi adicionado no filtro de data de atualização a opção de filtrar pelo ano atual.
