### ISSUE TITLE
Erro na paginação quando o resultado é exatamente um múltiplo de 10

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/centers-wp-plugin#20]
Vinícius,

Fiz uma pesquisa no Diretório da Rede BVS e o resultado são 20 instituições, mas carrega 3 páginas sendo que a última aparece em branco.

Segue a estratégia:

https://bvsalud.org/centros/results?lang=pt&q=mayor+san+andres

![image](https://user-images.githubusercontent.com/38661168/116103478-01259200-a686-11eb-85a2-c386e7c84066.png)

Obrigada!

**Comment by viniciusandrade** [comment]
@alvesmarilda correção realizada na paginação, quando possível favor validar.
Obrigado

**Comment by alvesmarilda** [comment]
Testes efetuado com sucesso.

Obrigada

**Comment by viniciusandrade** [comment]
Obrigado pela validação.
