### ISSUE TITLE
Busca diretório da Rede BVS País Brasil - duplicação resultado

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/centers-wp-plugin#22]
Por favor verificar o resultado de busca efetuada hoje, que mostra duplicação no resultado País=Brasil.

https://bvsalud.org/centros?lang=pt&q=user%3Arefnet+and+user%3Aredebr%2Fcc

![image](https://user-images.githubusercontent.com/38661168/128222407-b1cd5e57-dd5d-4a35-a721-4f46fa075fba.png)

Obrigada!

**Comment by viniciusandrade** [comment]
@alvesmarilda problema resolvido. 

Obrigado.
