### ISSUE TITLE
Criar cluster editores de revistas

### ISSUE THREAD

**Issue by suelisuga** [bireme/centers-wp-plugin#23]
Solicito criar cluster

- Editores de periódicos (PT)
- Editores de revistas (ES)
- Journal publishers (EN)

Incluir nesse cluster os registros marcados como categoria PERIODICOEDITOR

Obrigada!
Sueli

**Comment by viniciusandrade** [comment]
@alvesmarilda, poderia me ajudar a entender se esta solicitação já foi implementada quando fizemos a revisão recente do diretório e incluimos o item **Editor** no filtro **Rede BVS**, se trata da mesma coisa correto?

**Comment by viniciusandrade** [comment]
@suelisuga confirmei com a Marilda que na revisão recente dos filtro geral do diretório foi implementado o filtro pelos Editores, a única diferença é que ficou com o termo **Editor** e não **Editores de periódicos**  na interface:

![image](https://github.com/bireme/centers-wp-plugin/assets/349287/5f96fdfb-42fd-46fc-adbc-5dec0d72bbb9)

Caso tenha alguma consideração adicional favor re-abrir este issue. Obrigado.
