### ISSUE TITLE
Faltando apresentar o Status das bibliotecas "INATIVA ou FECHADA" ao lado do nome

### ISSUE THREAD

**Issue by marcoslmori** [bireme/centers-wp-plugin#27]
Instância antiga:  https://teste.bvsalud.org/centros

![image](https://github.com/bireme/centers-wp-plugin/assets/10047460/07ec8496-4b90-41f6-b966-2d1c24d52ff3)

Instância atual:  https://bvsalud.org/centros

![image](https://github.com/bireme/centers-wp-plugin/assets/10047460/4c1130a5-ea92-4a63-82d4-dee5592fb345)

**Comment by viniciusandrade** [comment]
@marcioalvessilva será que você consegue dar uma força neste issue aqui.

Quando eu faço o inspect da página vejo que os dados estão presentes mas não estão sendo apresentadas como na versão anterior devido a CSS.

Veja na imagem abaixo da versão anterior os elementos da numeração do card 1/1 e o status FECHADA estão usando a classe badge mas que tem outro comportamento na versão nova do portal

![image](https://github.com/bireme/centers-wp-plugin/assets/349287/c8be8fef-e053-4a2f-a261-0d9fc6499fec)

Links para o ambiente de teste para esta página na versão anterior e atual:

Versão anterior:
https://teste.bvsalud.org/centros/?lang=pt&q=mx3.1

Versão nova:
https://teste2023.bvsalud.org/centros/?lang=pt&q=mx3.1

Obrigado

**Comment by marcioalvessilva** [comment]
boa tarde, @viniciusandrade, só troca a classe "**badge badge-warning**" por "**badge text-bg-warning**".

**Comment by viniciusandrade** [comment]
Perfeito @marcioalvessilva ... já fiz o ajuste lá no template e esta apresentando corretamente a informação. Obrigado.

**Comment by viniciusandrade** [comment]
@marcoslmori favor solicitar a atualização da produção (git pull) e fechar este issue quando finalizado. Obrigado.

**Comment by marcoslmori** [comment]
atividade efetuada em 21/03/2024  no chamado 9628
