### ISSUE TITLE
Ajuste CSS

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/centers-wp-plugin#28]
Por favor inserir o código css para correção de alguns elementos

#speakBtn{
   display:none;
}
#header{
   margin-top:0;
}
.titleMain1{
   float:left;
   margin-bottom:30px;
}
.headerSearch{
   clear:both;
   margin-top:20px;
}
@media (max-width: 768px){
   .titleMain1{
      float:none;
      margin-top:20px;
      margin-bottom:0;
   }
}

**Comment by viniciusandrade** [comment]
@marcioalvessilva ajustes aplicados em teste. Obrigado pelos ajustes

@marcoslmori, favor solicitar o git pull na produção. Obrigado.

**Comment by marcoslmori** [comment]
Chamado aberto para o iti
http://suporte.bvs.br//ocomon/geral/ticket_show.php?numero=9628&id=qQNGych36AVNicOklRQb3h%2FPj6o%3D
