### ISSUE TITLE
Problemas no Layout

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/centers-wp-plugin#5]
Colegas,

Há links e textos passando da área determinada.

https://bvsalud.org/centros?filter=institution_type:%22CooperatingCentersLILACS%22

(https://user-images.githubusercontent.com/38661168/81079645-2d209400-8ec6-11ea-851b-803f12dc5c2f.png)

Obrigada

**Comment by viniciusandrade** [comment]
@marcioalvessilva 
Quando possível favor verificar e informar eventual ajuste necessário no código.

Obrigado

**Comment by viniciusandrade** [comment]
@alvesmarilda,
Poderia confirmar se o problema ainda ocorre? Verifiquei hoje que após ajustes aplicados no campo de contato e não identifiquei mais estes casos.
Obrigado

**Comment by alvesmarilda** [comment]
@viniciusandrade 

Verificação efetuada e conclui que o problema foi resolvido.

Obrigada

**Comment by viniciusandrade** [comment]
@alvesmarilda,
Obrigado pela verificação.

**Comment by alvesmarilda** [comment]
Os problemas no layout estão ocorrendo novamente.

![image](https://user-images.githubusercontent.com/38661168/86596566-cb85b000-bf70-11ea-8127-46d64872b19a.png)

![image](https://user-images.githubusercontent.com/38661168/86596675-025bc600-bf71-11ea-87a4-368fcc40ead7.png)

Obrigada!

**Comment by viniciusandrade** [comment]
@marcioalvessilva poderia dar uma olhada por favor?

**Comment by viniciusandrade** [comment]
Ajuste realizado na CSS por orientação do @marcioalvessilva :
```
.box1{
   ...
   word-break: break-word;
}
```
@alvesmarilda layout corrigido ... talvez seja necessário realizar SHIFT+REFRESH em seu navegador para pegar a correção do layout.

Obrigado.
