### ISSUE TITLE
Tipo de Usuário (users)  CC / UP ou Rede BVS

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/centers-wp-plugin#6]
Colegas,

Todos os usuários da lista apresentam o mesmo tipo(user).
Exemplos:
Vejo que todos os registros aparecem user=tipo (CC/UP/Rede BVS):

BR1.1
Centros Coordenadores Regionais
Centros Cooperantes
Centros Cooperantes LILACS
Unidades Participantes
Rede BVS

BR67.1
Centros Cooperantes
Centros Cooperantes LILACS
Unidades Participantes
Rede BVS

BR1354.1
Centros Cooperantes
Centros Cooperantes LILACS
Unidades Participantes
Rede BVS

BR1913.1
Centros Cooperantes
Unidades Participantes
Rede BVS

Rede BVS
**Centros Cooperantes (6221)**
**Unidades Participantes (6221)
Rede BVS (6221)**

**Comment by suelisuga** [comment]
Notei que o número de CC está igual ao de UP:
Centros Cooperantes (6222)
Unidades Participantes (6222)

Deve ser o mesmo problema identificado por @alvesmarilda 
Obrigada!

**Comment by viniciusandrade** [comment]
@alvesmarilda,
Revisei a geração do filtro Rede BVS e agora acredito que esteja OK.
Quando possível poderia verificar?
Obrigado.

**Comment by alvesmarilda** [comment]
@viniciusandrade 
Revisei o diretório e fiquei com dúvidas.
Não aparece alguns tipos de usuários:
Exemplo: Redext, Centros Coordenadores Temáticos, RefNet, Bibliosus etc..
Rede BVS (221) não está especificado os usuários..

No e-mail que você havia perguntado sobre estas questões respondemos:

A busca por tipo/user esta olhando somente para os campos antigos de histórico e deve ser usado com ":" por exemplo user:BIBLIOSUS. Favor indicar se podemos deixar de usar os campos antigos e usar as tabelas controladas para esta busca (favor abrir issue informando). Lembrando que caso mudemos para os novos campos não será possível buscar pelos valores do histórico ... podemos também tentar combinar os dois, favor informar a melhor opção no issue. **(tentar combinar os dois)**


Redes temáticas também esta olhando o campo antigo de tipo (histórico) e somente estão disponíveis as mesmas que eram apresentadas no portal antigo .. se apontarmos para campo controlado de tipo irão aparecer várias outras opções que não são redes, por exemplo: CCN, CCR, etc ... como podemos proceder neste caso? **(apontar para campo controlado de tipo e mostrar todos na opção Rede BVS, e neste caso retirar redes temáticas.)**
Será implementado a busca de todos os usuários??

**Comment by viniciusandrade** [comment]
@alvesmarilda 

Entendo sua dúvida porque eu também tenho dúvidas sobre este filtro ... o que acontece é que não é possível simplesmente mostrar todos os tipos presentes na lista controlada pois este mesmo campo  é usado para  Rede BVS e também Redes Temáticas.

Resumindo, temos que identificar quais são os valores que queremos mostrar no Diretório e qual a regra usar, abaixo esta a regra atual para sua revisão:

CASO **Tipo** tenha **CCR** ENTÃO -> Centros Coordenadores Regionais

CASO **Tipo** tenha **CCN** ENTÃO -> Centros Coordenadores Nacionais 

CASO **Tipo** tenha **REDEBR/CC** ou **REDEAL/CC** ou **MEDCARIB/CC** ENTÃO -> Centros Cooperantes

CASO **Tipo** tenha **LILACS** ENTÃO -> Centros Cooperantes LILACS

CASO **Tipo** tenha **LEYES** ENTÃO -> Centros Cooperantes LEYES

CASO **Tipo** tenha **REDEBR/UP** ou **REDEAL/UP** ou **MEDCARIB/UP** ENTÃO -> Unidades Participantes

CASO **Tipo** tenha **REDEAL** ou **REDEBR** ou **EPORT** ou **MEDCARIB** ENTÃO -> Rede BVS

* Vamos concentrar este issue em corrigir o filtro Rede BVS e depois passamos para outros temas.
* Caso ainda tenha ficado confuso pode marcar uma reunião no Teams para que eu possa tentar te explicar melhor

Obrigado.

**Comment by alvesmarilda** [comment]
@viniciusandrade 
ok!  Vou abrir outro issue para esta questão.

Obrigada

**Comment by viniciusandrade** [comment]
@alvesmarilda,

Obrigado.  Este issue você acredita que esteja OK? Ou seja, as regras que eu coloquei estão corretas e refletem os números apresentados no diretório?

Obrigado.

**Comment by alvesmarilda** [comment]
Sim, de acordo com as suas regras estão ok.

Obrigada

**Comment by viniciusandrade** [comment]
OK, obrigado ... vamos tratar sobre a reformulação dos filtros no issue #12 que você criou.
