### ISSUE TITLE
Problemas nos campos e-mail/tels (Layout)

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/centers-wp-plugin#8]
=Colegas,

Abaixo segue um exemplo de campos que se misturam(e-mail/tel) na tela de apresentação do diretório BVS:

PE18.1
Centros Cooperantes
Centros Cooperantes LILACS
Unidades Participantes
Rede BVS
Av Salaverrry 801 Jesús María - Lima - Peru - Perú
Alicia Ríos Terrones de Terranova **ariost@minsa.gob.pe**  _511 315-6600 Anexo 2001_
**biblioteca_bvs@minsa.gob.pe**

Abaixo copio tela da disposição dos campos no Fi-admin e tela de apresentação no diretório da rede.

![image](https://user-images.githubusercontent.com/38661168/81328808-e96b8d00-9073-11ea-9b58-270405bea98e.png)

Obrigada!

**Comment by viniciusandrade** [comment]
@alvesmarilda 
Adicionei o separador "|" entre as informações para facilitar a leitura. 
Infelizmente não é possível maiores ajustes devido ao dado migrado que contém muitas vezes os dados no mesmo campo separado por "; "

**Comment by alvesmarilda** [comment]
@viniciusandrade 

ok! validado.

Obrigada
