### ISSUE TITLE
Opção "início" página não carrega

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/centers-wp-plugin#9]
@viniciusandrade 
A opção "início" na página do diretório não carrega.

![image](https://user-images.githubusercontent.com/38661168/83895316-e7efbc00-a728-11ea-89d8-7861004b8044.png)

https://bvsalud.org/centros/Diret%C3%B3rio%20de%20Institui%C3%A7%C3%B5es%20Cooperantes

Obrigada!

**Comment by viniciusandrade** [comment]
@alvesmarilda 
Correção realizada.

Obrigado
